### ISSUE TITLE
国内电话号码正则匹配（三大运营商+虚拟等）

### ISSUE THREAD

**Issue by gongel** [fighting41love/funNLP#10]
[https://github.com/VincentSit/ChinaMobilePhoneNumberRegex](https://github.com/VincentSit/ChinaMobilePhoneNumberRegex)

**Comment by fighting41love** [comment]
Thanks for sharing! I will add this repo to funNLP in a few days.
Thanks!

**Comment by fighting41love** [comment]
I have added the repo to readme file.
