### ISSUE TITLE
第14链接地址都是404

### ISSUE THREAD

**Issue by baoerzhang** [fighting41love/funNLP#11]
大佬您好，第14链接地址都是404，请查实

**Comment by fighting41love** [comment]
您好！我查了一下，dongxiexidian 这个小伙好像在github上注销了or换名字了。
**可能是删库跑路了。**

通过google cache webpage，找到了fork的repo，链接如下：
https://github.com/fighting41love/Chinese_from_dongxiexidian

[反动词库， 敏感词库表统计， 暴恐词库， 民生词库， 色情词库](https://github.com/fighting41love/funNLP/tree/master/data/敏感词库) 主要在本repo的data 文件夹中。

**Comment by fighting41love** [comment]
本repo的data 文件夹中的 （反动词库， 敏感词库表统计， 暴恐词库， 民生词库， 色情词库 ）好像是我之前从他的repo中备份出来的。

**Comment by baoerzhang** [comment]
谢谢！
