### ISSUE TITLE
English support?

### ISSUE THREAD

**Issue by skynyrd** [fighting41love/funNLP#2]
Hi, I'm interested in your work but apparently, understood nothing. 🤕 
Do you consider adding some English translations?

Thanks.

**Comment by fighting41love** [comment]
Hi,
This is a Chinese-nlp repo. It contains word banks, specific indurstry/business word banks, poetry banks, the introduction of many interesting Chinese python packages. Most of the word banks, corpus and python package are used in Chinese related nlp tasks. There are also some English related python packages. For instance,  

- No.2: langid and langdetect, a python package, which can detect the language of the text, spanish? English?French? and many other 97 languages.
- No.5: phone, a python package, which can identify the location of the telephone number?
```
phone('+852` 6569-8900')
return ['+85265698900', `'HKG']
```
- No.7: the regex of email:  extract email address from texts
- No.10:  English-chinese name pairs:  John(English)--约翰(Chinese)，it also contains many Japanese names, in that Japanese is a language generated from Chinese.
- No.17: funny chinese text to speech engine, which is built by @tinyfool
```
English: I love you
say: wo i ni
#说：我爱你
```
- No.20: wordninja: probabilistically split concatenated words using NLP based on English Wikipedia unigram frequencies, which is built by @keredson.
```
import wordninja
wordninja.split('derekanderson')
['derek', 'anderson']
wordninja.split('imateapot')
['im', 'a', 'teapot']
```
-No.21: the regex of ip: extract IP address from texts

Hope this will be helpful.

**Comment by skynyrd** [comment]
Thank you very much, it is helpful.
