### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by bearDream** [fighting41love/funNLP#24]
经使用发现大部分文件是GBK编码，建议全部转换为UTF-8

**Comment by fighting41love** [comment]
已修改一部分文件的编码，后续会不断修正完毕。谢谢！

**Comment by fighting41love** [comment]
> 经使用发现大部分文件是GBK编码，建议全部转换为UTF-8

已全部修正至utf8编码，如有遗漏烦请指正。谢谢！
