### ISSUE TITLE
我贡献一个工具，中文数字提取转化阿拉伯数字的工具，已经在OCR，医疗，机器人领域应用很多了

### ISSUE THREAD

**Issue by Wall-ee** [fighting41love/funNLP#26]
中文转阿拉伯数字的工具  有python和go 语言版本
https://github.com/Wall-ee/chinese2digits

**Comment by fighting41love** [comment]
> 中文转阿拉伯数字的工具 有python和go 语言版本
> https://github.com/Wall-ee/chinese2digits

Great repo. Thanks for sharing! I will add your repo to funNLP soon.
