### ISSUE TITLE
Which kind of model is better for keyword-set classification?

### ISSUE THREAD

**Issue by guotong1988** [fighting41love/funNLP#28]
There exists a similar task that is named text classification.

But I want to find a kind of model that the inputs are keyword set. And the keyword set is not from a sentence.

For example:
```
input ["apple", "pear", "water melon"] --> target class "fruit"
input ["tomato", "potato"] --> target class "vegetable"
```
Another example:
```
input ["apple", "Peking", "in summer"]  -->  target class "Chinese fruit"
input ["tomato", "New York", "in winter"]  -->  target class "American vegetable"
input ["apple", "Peking", "in winter"]  -->  target class "Chinese fruit"
input ["tomato", "Peking", "in winter"]  -->  target class "Chinese vegetable"
```
Thank you.

**Comment by fighting41love** [comment]
1. If you don't have any labels, you can try some clustering methods with pre-trained embedding.
2. If you have labels for each input, just try simple lstm and textcnn models.
