### ISSUE TITLE
大佬敏感词汇中有部分乱码可以进行更正下吗

### ISSUE THREAD

**Issue by ICLXL** [fighting41love/funNLP#30]
�H
![image](https://user-images.githubusercontent.com/30027321/71762772-7956ca00-2f0e-11ea-8bce-d111d0ebf43e.png)

**Comment by fighting41love** [comment]
已更正，感谢指正！

> �H
> ![image](https://user-images.githubusercontent.com/30027321/71762772-7956ca00-2f0e-11ea-8bce-d111d0ebf43e.png)

已更正，感谢指正！
