### ISSUE TITLE
一个中文关键短语抽取工具

### ISSUE THREAD

**Issue by dongrixinyu** [fighting41love/funNLP#32]
一个中午关键短语抽取工具
https://github.com/dongrixinyu/chinese_keyphrase_extractor

这个是我自己写的，效果可以尝试，希望能够加进去，谢谢

**Comment by fighting41love** [comment]
好的，感谢分享，我再下一个版本中加入哈。敬请期待。

**Comment by dongrixinyu** [comment]
好的，非常感谢啦！

**Comment by fighting41love** [comment]
已添加，感谢分享！！！
