### ISSUE TITLE
敏感词词库乱码

### ISSUE THREAD

**Issue by bin20060407** [fighting41love/funNLP#37]
![image](https://user-images.githubusercontent.com/2154817/80301834-f61cf500-87d8-11ea-804f-a29c59068418.png)

如上图

**Comment by fighting41love** [comment]
已修正。。。感谢指正！

**Comment by bin20060407** [comment]
pull 了，核对了一下，乱码并没有修正掉

**Comment by fighting41love** [comment]
> pull 了，核对了一下，乱码并没有修正掉

实在是没找到办法解决该问题，故上传了两个词表的doc版本，并说明了原txt的编码格式（gbk）。。。
