### ISSUE TITLE
推荐工具和语料

### ISSUE THREAD

**Issue by KuangDD** [fighting41love/funNLP#42]
您好，请看看以下工具和语料有没有用？

1. zhrtvc
https://github.com/KuangDD/zhrtvc
Chinese real time voice cloning and Chinese TTS. 好用的中文语音克隆兼中文语音合成系统。

2. aukit
https://github.com/KuangDD/aukit
audio toolkit. 好用的语音处理工具箱，包含语音降噪、音频格式转换、特征频谱生成等模块。

3. phkit
https://github.com/KuangDD/phkit
phoneme toolkit. 好用的音素处理工具箱，包含中文音素、英文音素、文本转拼音、文本正则化等模块。

4. zhvoice
https://github.com/KuangDD/zhvoice
Chinese voice corpus. 中文语音语料，语音更加清晰自然，包含8个开源数据集，3200个说话人，900小时语音，1300万字。

**Comment by fighting41love** [comment]
> 您好，请看看以下工具和语料有没有用？
> 
> 1. zhrtvc
>    https://github.com/KuangDD/zhrtvc
>    Chinese real time voice cloning and Chinese TTS. 好用的中文语音克隆兼中文语音合成系统。
> 2. aukit
>    https://github.com/KuangDD/aukit
>    audio toolkit. 好用的语音处理工具箱，包含语音降噪、音频格式转换、特征频谱生成等模块。
> 3. phkit
>    https://github.com/KuangDD/phkit
>    phoneme toolkit. 好用的音素处理工具箱，包含中文音素、英文音素、文本转拼音、文本正则化等模块。
> 4. zhvoice
>    https://github.com/KuangDD/zhvoice
>    Chinese voice corpus. 中文语音语料，语音更加清晰自然，包含8个开源数据集，3200个说话人，900小时语音，1300万字。

非常赞！感谢分享，将会很快更新到repo中。
