### ISSUE TITLE
人肉支持打破0issue

### ISSUE THREAD

**Issue by yeayi** [fighting41love/funNLP#5]
感谢fighting41love

**Comment by fighting41love** [comment]
Thanks!  Your comment is a great spur to me. I will continue to collect more corpus. Hope this will help nlper a lot. Thanks! 
`
如果你读了篇论文或博客，发现很有用，最好能给作者发个简单的邮件，告诉他们。撰写长篇技术内容非常不易，作者可能会系统性低估他们创造内容的价值。 via: Sean J. Taylor ​​​​
`
Pls ignore the unfriendly thumb down by ritterhou.

**Comment by upccup** [comment]
> Thanks! Your comment is a great spur to me. I will continue to collect more corpus. Hope this will help nlper a lot. Thanks!
> `如果你读了篇论文或博客，发现很有用，最好能给作者发个简单的邮件，告诉他们。撰写长篇技术内容非常不易，作者可能会系统性低估他们创造内容的价值。 via: Sean J. Taylor ​​​​`
> Pls ignore the unfriendly thumb down by ritterhou.

github 真是个神奇的网站

**Comment by cj7654321** [comment]
点赞下，挺好的

**Comment by x11wu** [comment]
感谢楼主的分享

**Comment by zhe-he** [comment]
好人一生平安😏

**Comment by JZ-2018** [comment]
Gracias,:wink:
