### ISSUE TITLE
建议码云啥的弄一个   省的美国人屏蔽攻击咱啥的  美国人不可靠

### ISSUE THREAD

**Issue by sizhongyibanhts** [fighting41love/funNLP#60]

**Comment by erbanku** [comment]
只想说一声“呵呵”，不知水太深？码云搞上去分分钟钟教你做人，国内不会允许，这算是泄密

**Comment by sizhongyibanhts** [comment]
马云有啥问题？发自我的荣耀手机-------- 原始邮件 --------发件人： Cactus ***@***.***>日期： 2021年4月30日周五 10:25收件人： fighting41love/funNLP ***@***.***>抄送： Han Tianshuo ***@***.***>, Author ***@***.***>主    题： Re: [fighting41love/funNLP] 建议码云啥的弄一个   省的美国人屏蔽攻击咱啥的  美国人不可靠 (#60)

只想说一声“呵呵”，不知水太深？码云搞上去分分钟钟教你做人，国内不会允许，这算是泄密
