### ISSUE TITLE
求求您，给这个README排个版吧……

### ISSUE THREAD

**Issue by LaoshuBaby** [fighting41love/funNLP#65]
这主页看上去太死亡了！SEO关键词优化也没这么叠杀人书的啊……

![图片](https://user-images.githubusercontent.com/42690037/130635648-4bc9274d-b44f-4f6a-b9b6-32ff824fa7db.png)

**Comment by LaiHongtao** [comment]
哈哈哈哈哈哈叠杀人书可太搞笑了

**Comment by Dicer-Zz** [comment]
笑死了😆

**Comment by Mike-Z9986** [comment]
哈哈哈readme直接劝退我

**Comment by LongwayCHOW** [comment]
你发的邮件我已收到，并且尽快取阅，感谢你的来信，祝你愉快~

**Comment by Hao813** [comment]
笑死我了

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zxw254470434** [comment]
hhhhhhh,翻到下面我直接一脸懵逼，这是我见过最乱的readme了

**Comment by LongwayCHOW** [comment]
你发的邮件我已收到，并且尽快取阅，感谢你的来信，祝你愉快~

**Comment by lvxiaojie111** [comment]
您的邮件已经收到。谢谢！                                          吕

**Comment by fwindpeak** [comment]
我觉得还好啊，反正都是cmd+f，这样节省空间 😄

**Comment by lnest** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
尽快给您回复。

**Comment by fighting41love** [comment]
已重新排版，感谢建议与支持！
