### ISSUE TITLE
敏感词库

### ISSUE THREAD

**Issue by grygg** [fighting41love/funNLP#66]
为何敏感词库del了呢

**Comment by Wenju-Huang** [comment]
同求敏感词

**Comment by fighting41love** [comment]
敏感词因有潜在社会危害，已被删除。。。请各位想想别的办法。

**Comment by zoujiawei6** [comment]
> 敏感词因有潜在社会危害，已被删除。。。请各位想想别的办法。

确实无法区分使用者是敌是友，就如同[clowwindy](https://github.com/clowwindy)一样选择删掉ss才是最好的选择。

**Comment by lilipopololo** [comment]
建议看看https://chinadigitaltimes.net/ 中国数字时代的敏感词统计
