### ISSUE TITLE
奈学教育真垃圾

### ISSUE THREAD

**Issue by ltnil** [fighting41love/funNLP#73]
奈学教育说话不算话，承诺返费各种延期后，又找各种理由不返费，最垃圾的平台，大家别轻易上当

**Comment by funny-cat-happy** [comment]
？？？奈学教育关这个项目什么事

**Comment by lvxiaojie111** [comment]
您的邮件已经收到。谢谢！                                          吕

**Comment by LongwayCHOW** [comment]
你发的邮件我已收到，并且尽快取阅，感谢你的来信，祝你愉快~

**Comment by cuizhenjie** [comment]
...
