### ISSUE TITLE
您好，中文问答数据集链接失效了可以再提供一下吗？

### ISSUE THREAD

**Issue by xuhongtian** [fighting41love/funNLP#79]

**Comment by lvxiaojie111** [comment]
您的邮件已经收到。谢谢！                                          吕

**Comment by LongwayCHOW** [comment]
你发的邮件我已收到，并且尽快取阅，感谢你的来信，祝你愉快~

**Comment by fighting41love** [comment]
https://pan.baidu.com/share/init?surl=QUsKcFWZ7Tg1dk_AbldZ1A 后续会更新到readme中

**Comment by xuhongtian** [comment]
谢谢谢，
在请教下网盘链接密码多少呗


资深老腊肉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fighting41love/funNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fighting41love/funNLP] 您好，中文问答数据集链接失效了可以再提供一下吗？ (Issue #79)





 
https://pan.baidu.com/share/init?surl=QUsKcFWZ7Tg1dk_AbldZ1A 后续会更新到readme中

**Comment by fighting41love** [comment]
> 谢谢谢， 在请教下网盘链接密码多少呗 资深老腊肉 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fighting41love/funNLP" ***@***.***&gt;; 发送时间:&nbsp;2022年11月15日(星期二) 中午1:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fighting41love/funNLP] 您好，中文问答数据集链接失效了可以再提供一下吗？ (Issue #79) https://pan.baidu.com/share/init?surl=QUsKcFWZ7Tg1dk_AbldZ1A 后续会更新到readme中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

repo的readme中有提取码，请查看readme
