### ISSUE TITLE
  让人人都变得“彬彬有礼”礼貌迁移任务， 地址无效： Article identifier '200414257' not recognized

### ISSUE THREAD

**Issue by chenbihao** [fighting41love/funNLP#83]
让人人都变得“彬彬有礼”礼貌迁移任务  

https://arxiv.org/abs/200414257 地址无效

 ： Article identifier '200414257' not recognized

**Comment by fighting41love** [comment]
> 让人人都变得“彬彬有礼”礼貌迁移任务
> 
> https://arxiv.org/abs/200414257 地址无效
> 
> ： Article identifier '200414257' not recognized

https://arxiv.org/abs/2004.14257，我将会在后续版本中修复该问题，丢失了一个.
