### ISSUE TITLE
MiningZhiDaoQACorpus数据集链接失效

### ISSUE THREAD

**Issue by Victoriaheiheihei** [fighting41love/funNLP#89]
hello，
感谢你的整理与分享，但似乎[MiningZhiDaoQACorpus](https://link.zhihu.com/?target=https%3A//github.com/liuhuanyong/MiningZhiDaoQACorpus),这个数据集链接失效了，请问还有什么有效的链接嘛

**Comment by fighting41love** [comment]
抱歉，这个没有备份数据，可以联系原作者：刘焕勇，中国科学院软件研究所，[lhy_in_blcu@126.com](mailto:lhy_in_blcu@126.com)

**Comment by lvxiaojie111** [comment]
您的邮件已经收到。谢谢！                                          吕

**Comment by LongwayCHOW** [comment]
你发的邮件我已收到，并且尽快取阅，感谢你的来信，祝你愉快~
